### ISSUE TITLE
Integrating with composer

### ISSUE THREAD

**Issue by josergcatmisatravelcom** [andrefigueira/geonames#1]
Hello!

Thanks for your library!

When I try to integrate your library using composer with the command "composer require andrefigueira/geonames", I get the message

  [InvalidArgumentException]
  Could not find package andrefigueira/geonames at any version for your minim
  um-stability (stable). Check the package spelling or your minimum-stability

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

Then when I try to integrate it with the command "composer require andrefigueira/geonames 1.0.0" I get this other message:
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package andrefigueira/geonames could not be found in any ver
sion, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.

Best regards,

José

**Comment by andrefigueira** [comment]
Hi José,

Try this instead: `composer require geonames/client 1.0.0`

I'll update the readme

Cheers

**Comment by misatravel** [comment]
oh! right! thank you very much! :+1:
